/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ed221ee9-0af8-4e3e-b94f-a6d05e8a4e5c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_LsT2WI074",
    "aws_user_pools_web_client_id": "16uukb8257p6elfdhs4fafhql5",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ujothh4abzeebcxqcj7yxhqmue.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
